import type { SourceExclusionAudit, SourceExclusionAuditCount } from "./types";

const DEFAULT_COMMENT_MARKERS = ["@generated", "<auto-generated"] as const;
const DECLARATION_FILE_SUFFIXES = [".d.ts", ".d.mts", ".d.cts"] as const;
const GENERATED_FILE_SUFFIXES = [
  ".generated.ts",
  ".generated.tsx",
  ".gen.ts",
  ".gen.tsx"
] as const;
const GENERATED_DIRECTORY_SEGMENTS = new Set([
  "generated",
  "__generated__",
  "dist",
  "build",
  "out",
  "coverage",
  "node_modules",
  "target",
  ".next",
  ".nuxt",
  ".svelte-kit"
]);
const TEST_FILE_MARKERS = [".test.", ".spec."] as const;

export interface SourceExclusionOptions {
  excludes: string[];
  excludeNames: string[];
  excludeDecorators: string[];
  excludeComments: string[];
  useDefaultExclusions: boolean;
}

export interface SourceExclusionCandidateMethod {
  functionName: string;
  displayName: string;
  exclusionNames: string[];
  decoratorNames: string[];
  leadingCommentText: string;
}

interface GlobRule {
  raw: string;
  regex: RegExp;
}

interface NameRule {
  raw: string;
  regex: RegExp;
}

export function resolveSourceExclusionOptions(options: Partial<SourceExclusionOptions>): SourceExclusionOptions {
  return {
    excludes: normalizeList(options.excludes),
    excludeNames: normalizeList(options.excludeNames),
    excludeDecorators: normalizeList(options.excludeDecorators),
    excludeComments: normalizeList(options.excludeComments),
    useDefaultExclusions: options.useDefaultExclusions ?? true
  };
}

export class SourceExclusionMatcher {
  private readonly pathRules: GlobRule[];
  private readonly nameRules: NameRule[];
  private readonly decoratorNames: string[];
  private readonly commentMarkers: string[];

  constructor(private readonly options: SourceExclusionOptions) {
    this.pathRules = options.excludes.map((pattern) => ({
      raw: pattern,
      regex: compileGlobPattern(pattern)
    }));
    this.nameRules = options.excludeNames.map((pattern) => ({
      raw: pattern,
      regex: compileNamePattern(pattern)
    }));
    this.decoratorNames = options.excludeDecorators;
    this.commentMarkers = [
      ...(options.useDefaultExclusions ? DEFAULT_COMMENT_MARKERS : []),
      ...options.excludeComments
    ];
  }

  fileExclusionReason(relativePath: string, leadingCommentText: string): string | null {
    const normalizedPath = normalizePath(relativePath);
    if (this.options.useDefaultExclusions) {
      const defaultReason = defaultFileExclusionReason(normalizedPath);
      if (defaultReason) {
        return defaultReason;
      }
    }

    for (const rule of this.pathRules) {
      if (rule.regex.test(normalizedPath)) {
        return `user:path:${rule.raw}`;
      }
    }

    return markerReason(this.commentMarkers, leadingCommentText, this.options.useDefaultExclusions);
  }

  functionExclusionReason(method: SourceExclusionCandidateMethod): string | null {
    for (const rule of this.nameRules) {
      if (method.exclusionNames.some((name) => rule.regex.test(name))) {
        return `user:name:${rule.raw}`;
      }
    }

    for (const configured of this.decoratorNames) {
      if (method.decoratorNames.some((decoratorName) => matchesDecoratorName(decoratorName, configured))) {
        return `user:decorator:${configured}`;
      }
    }

    return markerReason(this.commentMarkers, method.leadingCommentText, this.options.useDefaultExclusions);
  }
}

export class SourceExclusionAuditBuilder {
  private discoveredFiles = 0;
  private analyzedFiles = 0;
  private analyzedFunctions = 0;
  private readonly excludedFileReasons = new Map<string, number>();
  private readonly excludedFunctionReasons = new Map<string, number>();

  recordDiscoveredFiles(count: number): void {
    this.discoveredFiles += count;
  }

  recordAnalyzedFile(): void {
    this.analyzedFiles += 1;
  }

  recordAnalyzedFunction(): void {
    this.analyzedFunctions += 1;
  }

  recordExcludedFile(reason: string): void {
    increment(this.excludedFileReasons, reason);
  }

  recordExcludedFunction(reason: string): void {
    increment(this.excludedFunctionReasons, reason);
  }

  build(): SourceExclusionAudit {
    return {
      discoveredFiles: this.discoveredFiles,
      analyzedFiles: this.analyzedFiles,
      analyzedFunctions: this.analyzedFunctions,
      excludedFiles: totalCount(this.excludedFileReasons),
      excludedFunctions: totalCount(this.excludedFunctionReasons),
      excludedFileReasons: toCounts(this.excludedFileReasons),
      excludedFunctionReasons: toCounts(this.excludedFunctionReasons)
    };
  }
}

function normalizeList(values: string[] | undefined): string[] {
  return (values ?? [])
    .map((value) => value.trim())
    .filter((value) => value.length > 0);
}

function defaultFileExclusionReason(normalizedPath: string): string | null {
  if (DECLARATION_FILE_SUFFIXES.some((suffix) => normalizedPath.endsWith(suffix))) {
    return "default:path:declaration-file";
  }
  if (GENERATED_FILE_SUFFIXES.some((suffix) => normalizedPath.endsWith(suffix))) {
    return "default:path:generated-file";
  }
  if (hasGeneratedDirectorySegment(normalizedPath)) {
    return "default:path:generated-directory";
  }
  if (normalizedPath.includes("/__tests__/")) {
    return "default:path:test-directory";
  }
  if (TEST_FILE_MARKERS.some((marker) => baseName(normalizedPath).includes(marker))) {
    return "default:path:test-file";
  }
  return null;
}

function hasGeneratedDirectorySegment(normalizedPath: string): boolean {
  return normalizedPath
    .split("/")
    .slice(0, -1)
    .some((segment) => GENERATED_DIRECTORY_SEGMENTS.has(segment));
}

function baseName(normalizedPath: string): string {
  const segments = normalizedPath.split("/");
  return segments[segments.length - 1] ?? normalizedPath;
}

function markerReason(
  markers: readonly string[],
  leadingCommentText: string,
  useDefaultExclusions: boolean
): string | null {
  const normalizedComments = leadingCommentText.toLowerCase();
  for (const marker of markers) {
    if (normalizedComments.includes(marker.toLowerCase())) {
      const origin = useDefaultExclusions && DEFAULT_COMMENT_MARKERS.includes(marker as (typeof DEFAULT_COMMENT_MARKERS)[number])
        ? "default"
        : "user";
      return `${origin}:comment:${marker}`;
    }
  }
  return null;
}

function matchesDecoratorName(decoratorName: string, configured: string): boolean {
  return decoratorName === configured || simpleName(decoratorName) === configured;
}

function simpleName(value: string): string {
  const segments = value.split(".");
  return segments[segments.length - 1] ?? value;
}

function normalizePath(relativePath: string): string {
  return relativePath.replace(/\\/g, "/").toLowerCase();
}

function compileGlobPattern(pattern: string): RegExp {
  return new RegExp(`^${globToRegexSource(normalizePath(pattern))}$`);
}

function globToRegexSource(pattern: string): string {
  let source = "";
  for (let index = 0; index < pattern.length; index += 1) {
    const character = pattern[index];
    if (character === "*") {
      if (pattern[index + 1] === "*") {
        source += ".*";
        index += 1;
      } else {
        source += "[^/]*";
      }
      continue;
    }
    if (character === "?") {
      source += "[^/]";
      continue;
    }
    source += escapeRegexCharacter(character);
  }
  return source;
}

function compileNamePattern(pattern: string): RegExp {
  try {
    return new RegExp(pattern);
  } catch (error) {
    throw new Error(`Invalid exclude-name regex: ${pattern}`, { cause: error });
  }
}

function escapeRegexCharacter(character: string): string {
  return /[|\\{}()[\]^$+?.]/.test(character) ? `\\${character}` : character;
}

function increment(counts: Map<string, number>, reason: string): void {
  counts.set(reason, (counts.get(reason) ?? 0) + 1);
}

function totalCount(counts: Map<string, number>): number {
  return Array.from(counts.values()).reduce((sum, count) => sum + count, 0);
}

function toCounts(counts: Map<string, number>): SourceExclusionAuditCount[] {
  return Array.from(counts.entries())
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([reason, count]) => ({ reason, count }));
}
